apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/FuzzyNovaGoblin/test_argo_cd_manifest.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolyicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
